/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import controle.ManipularImagem;
import controle.ModeloTabela;
import modelo.Connection.Conecta;
import modelo.DAO.ProdutoDAO;
import modelo.Beans.Produto;

/**
 *
 * @author FamiliaPereira
 */
public class TelaProdutos extends javax.swing.JFrame {

    Produto prod = new Produto();
    ProdutoDAO produtoBD = new ProdutoDAO();
    Conecta conexaoBD = new Conecta();
    int flag = 0;

    BufferedImage imagem;

    public TelaProdutos() {
        initComponents();
        preencherTabela("SELECT * from produto order by nome_produto");

        jTextFieldNome.setEnabled(false);
        jTextFieldSigla.setEnabled(false);
        jTextFieldCategoria.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldComprimento.setEnabled(false);
        jTextFieldLargura.setEnabled(false);
        jTextFieldAltura.setEnabled(false);
        jTextFieldPreco.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

        jTextFieldNome.setText("");
        jTextFieldSigla.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldComprimento.setText("");
        jTextFieldLargura.setText("");
        jTextFieldAltura.setText("");
        jTextFieldPreco.setText("");

        jLabelImagem.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSigla = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldComprimento = new javax.swing.JTextField();
        jTextFieldLargura = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonPesquisa = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jButtonCancelar = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonAtualizarLista = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sessão Produtos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 20, 280, 50);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 183, 53, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(319, 183, 59, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(484, 180, 71, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descrição");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 390, 94, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Comprimento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 250, 88, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Largura");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 250, 66, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Altura");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 250, 53, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Preço");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 300, 53, 20);

        jTextFieldNome.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(67, 174, 209, 29);

        jTextFieldSigla.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldSigla.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldSigla);
        jTextFieldSigla.setBounds(382, 173, 69, 30);

        jTextFieldCategoria.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldCategoria);
        jTextFieldCategoria.setBounds(559, 173, 151, 30);

        jTextFieldComprimento.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldComprimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldComprimento.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldComprimento);
        jTextFieldComprimento.setBounds(108, 239, 89, 30);

        jTextFieldLargura.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldLargura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldLargura.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldLargura);
        jTextFieldLargura.setBounds(316, 239, 66, 30);

        jTextFieldPreco.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldPreco.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldPreco);
        jTextFieldPreco.setBounds(67, 299, 209, 30);

        jTextFieldAltura.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAltura.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldAltura);
        jTextFieldAltura.setBounds(510, 240, 65, 30);

        jTextFieldDescricao.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(40, 440, 308, 82);

        jButtonSalvar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/diskette.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(119, 11, 91, 67);

        jButtonNovo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNovo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(10, 10, 91, 70);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 221, 728, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(10, 287, 728, 16);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(10, 340, 728, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pesquisar (Código do Produto):");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 110, 200, 22);

        jTextFieldPesquisa.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(228, 103, 90, 30);

        jButtonEditar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(230, 10, 91, 67);

        jButtonExcluir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(337, 11, 91, 67);

        jButtonPesquisa.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/research.png"))); // NOI18N
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisa);
        jButtonPesquisa.setBounds(330, 103, 40, 30);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(10, 153, 725, 10);

        jButtonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(446, 11, 91, 67);

        jLabelImagem.setBackground(new java.awt.Color(0, 0, 0));
        jLabelImagem.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabelImagem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImagem.setText("CLIQUE AQUI PARA INSERIR A IMAGEM DO PRODUTO");
        jLabelImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagemMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelImagem);
        jLabelImagem.setBounds(390, 350, 370, 250);

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo Produto", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        jButtonAtualizarLista.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAtualizarLista.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh.png"))); // NOI18N
        jButtonAtualizarLista.setText("Atualizar Lista");
        jButtonAtualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAtualizarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAtualizarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabela de Produtos", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 90, 780, 630);

        jButtonSair.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(30, 10, 80, 70);

        jLabelBackground.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.png"))); // NOI18N
        jLabelBackground.setText("Produtos");
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, -10, 1220, 820);

        setSize(new java.awt.Dimension(847, 777));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 1) {
            try {
                prod.setNomeProd(jTextFieldNome.getText());
                prod.setSiglaProd(jTextFieldSigla.getText());
                prod.setCategoriaProd(jTextFieldCategoria.getText());
                prod.setDescProd(jTextFieldDescricao.getText());
                prod.setCompProd(Double.parseDouble(jTextFieldComprimento.getText()));
                prod.setLargProd(Double.parseDouble(jTextFieldLargura.getText()));
                prod.setAltProd(Double.parseDouble(jTextFieldAltura.getText()));
                prod.setPrecoProd(Double.parseDouble(jTextFieldPreco.getText()));
                prod.setImagem(ManipularImagem.getImgBytes(imagem));

                produtoBD.Salvar(prod);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Não foi possivel gravar objeto.");
            }
        } else {
            prod.setNomeProd(jTextFieldNome.getText());
            prod.setSiglaProd(jTextFieldSigla.getText());
            prod.setCategoriaProd(jTextFieldCategoria.getText());
            prod.setDescProd(jTextFieldDescricao.getText());
            prod.setCompProd(Double.parseDouble(jTextFieldComprimento.getText()));
            prod.setLargProd(Double.parseDouble(jTextFieldLargura.getText()));
            prod.setAltProd(Double.parseDouble(jTextFieldAltura.getText()));
            prod.setPrecoProd(Double.parseDouble(jTextFieldPreco.getText()));
            prod.setImagem(ManipularImagem.getImgBytes(imagem));

            produtoBD.editaProduto(prod);
        }
        jTextFieldNome.setEnabled(false);
        jTextFieldSigla.setEnabled(false);
        jTextFieldCategoria.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldComprimento.setEnabled(false);
        jTextFieldLargura.setEnabled(false);
        jTextFieldAltura.setEnabled(false);
        jTextFieldPreco.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisa.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);

        jTextFieldNome.requestFocus();

        jTextFieldNome.setText("");
        jTextFieldSigla.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldComprimento.setText("");
        jTextFieldLargura.setText("");
        jTextFieldAltura.setText("");
        jTextFieldPreco.setText("");

        jLabelImagem.setIcon(null);
        jLabelImagem.revalidate();
        jLabelImagem.setVisible(false);

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        flag = 1;

        jTextFieldNome.setEnabled(true);
        jTextFieldSigla.setEnabled(true);
        jTextFieldCategoria.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jTextFieldComprimento.setEnabled(true);
        jTextFieldLargura.setEnabled(true);
        jTextFieldAltura.setEnabled(true);
        jTextFieldPreco.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonPesquisa.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);

        jLabelImagem.setVisible(true);

        jTextFieldNome.setText("");
        jTextFieldSigla.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldComprimento.setText("");
        jTextFieldLargura.setText("");
        jTextFieldAltura.setText("");
        jTextFieldPreco.setText("");

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();

        Principal telaPrincipal = new Principal();
        telaPrincipal.setVisible(true);

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        flag = 2;

        jTextFieldNome.setEnabled(true);
        jTextFieldSigla.setEnabled(true);
        jTextFieldCategoria.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jTextFieldComprimento.setEnabled(true);
        jTextFieldLargura.setEnabled(true);
        jTextFieldAltura.setEnabled(true);
        jTextFieldPreco.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonPesquisa.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jLabelImagem.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;

        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o objeto?");

        if (resposta == JOptionPane.YES_OPTION) {
            prod.setSiglaProd(jTextFieldSigla.getText());
            produtoBD.excluiProduto(prod);
        }

        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);


        jTextFieldNome.setText("");
        jTextFieldSigla.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldComprimento.setText("");
        jTextFieldLargura.setText("");
        jTextFieldAltura.setText("");
        jTextFieldPreco.setText("");
        jTextFieldPesquisa.setText("");

        jLabelImagem.setIcon(null);
        jLabelImagem.revalidate();
        jLabelImagem.setVisible(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed

        if ("".equals(jTextFieldPesquisa.getText())) {
            JOptionPane.showMessageDialog(null, "O campo de pesquisa não pode ficar vazio.");
        } else {
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonNovo.setEnabled(false);

            prod.setPesquisa(jTextFieldPesquisa.getText());
            Produto modelo = produtoBD.buscaProduto(prod);
            jTextFieldNome.setText(modelo.getNomeProd());
            jTextFieldSigla.setText(modelo.getSiglaProd());
            jTextFieldCategoria.setText(modelo.getCategoriaProd());
            jTextFieldDescricao.setText(modelo.getDescProd());
            jTextFieldComprimento.setText(String.valueOf(modelo.getCompProd()));
            jTextFieldLargura.setText(String.valueOf(modelo.getLargProd()));
            jTextFieldAltura.setText(String.valueOf(modelo.getAltProd()));
            jTextFieldPreco.setText(String.valueOf(modelo.getPrecoProd()));
            jLabelImagem.setText("");
            jLabelImagem.setVisible(true);
            ManipularImagem.exibiImagemLabel(prod.getImagem(), jLabelImagem);

        }
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(false);
        jTextFieldSigla.setEnabled(false);
        jTextFieldCategoria.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldComprimento.setEnabled(false);
        jTextFieldLargura.setEnabled(false);
        jTextFieldAltura.setEnabled(false);
        jTextFieldPreco.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisa.setEnabled(true);

        jTextFieldNome.setText("");
        jTextFieldSigla.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldComprimento.setText("");
        jTextFieldLargura.setText("");
        jTextFieldAltura.setText("");
        jTextFieldPreco.setText("");
        jTextFieldPesquisa.setText("");

        jLabelImagem.setIcon(null);
        jLabelImagem.revalidate();
        jLabelImagem.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAtualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarListaActionPerformed
        preencherTabela("SELECT * from produto order by nome_produto");
    }//GEN-LAST:event_jButtonAtualizarListaActionPerformed

    private void jLabelImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagemMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja adicionar uma imagem ao produto?", "Atenção!", dialogButton);

        if (dialogResult == JOptionPane.YES_OPTION) {
            JFileChooser fc = new JFileChooser();
            int res = fc.showOpenDialog(null);

            if (res == JFileChooser.APPROVE_OPTION) {
                File arquivo = fc.getSelectedFile();

                try {
                    imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 320, 320);

                    jLabelImagem.setIcon(new ImageIcon(imagem));

                    jLabelImagem.setText("");

                } catch (Exception ex) {
                    // System.out.println(ex.printStackTrace().toString());
                }

            } else {
                JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
            }
        }

    }//GEN-LAST:event_jLabelImagemMouseClicked

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Codigo", "Nome", "Descrição"};
        conexaoBD.conexao();
        conexaoBD.executaSql(sql);

        try {
            conexaoBD.rs.first();
            do {
                dados.add(new Object[]{conexaoBD.rs.getString("sigla_produto"), conexaoBD.rs.getString("nome_produto"), conexaoBD.rs.getString("descricao_produto")});
            } while (conexaoBD.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao carregar tabela");
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableProdutos.setModel(modelo);
        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableProdutos.getColumnModel().getColumn(1).setResizable(false);
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(500);
        jTableProdutos.getColumnModel().getColumn(2).setResizable(false);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.setAutoResizeMode(jTableProdutos.AUTO_RESIZE_OFF);
        jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conexaoBD.desconectar();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarLista;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldComprimento;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldLargura;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldSigla;
    // End of variables declaration//GEN-END:variables
}
